### ISSUE TITLE
I got a 403 error

### ISSUE THREAD

**Issue by fiatjaf** [encukou/lastscrape-gui#8]
> Please report the bug at:
> http://bugs.foocorp.net/projects/lastscrape-gui/issues/new

```python
Traceback (most recent call last):
  File "gui.py", line 344, in run
    sleep_func=lambda s: self.msleep(int(s * 1000)),
  File "/home/fiatjaf/Desktop/encukou-lastscrape-gui-63a1f19/lastexport.py", line 165, in get_tracks
    response =  connect_server(server, username, page, sleep_func, tracktype)
  File "/home/fiatjaf/Desktop/encukou-lastscrape-gui-63a1f19/lastexport.py", line 93, in connect_server
    raise last_exc
HTTPError: HTTP Error 403: Forbidden
```

**Comment by fiatjaf** [comment]
Is there a way to try again later, without losing is already scraped?

**Comment by encukou** [comment]
Are you getting the "Forbidden" error in the middle of scraping, after the first few pages were scraped?

There is no resume functionality I'm afraid.

**Comment by fiatjaf** [comment]
I got it in the end, when I imagined it was almost finishing. Maybe it has completed the scrapping and the error was just a misnomer, because I haven't really inspected the result. I'll do it.

**Comment by fiatjaf** [comment]
The next time I tried it worked well.
